# -*- coding: utf-8 -*-
"""Prodigy_T1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b9W2PzpwYVEwTuw6PTy_fIrU_LWQLr8C
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the movie dataset
file_path = 'movies.csv'
movies_df = pd.read_csv('movie.csv')

# Display the first few rows of the dataset
print("First few rows of the movie dataset:")
print(movies_df.head())

# Check for missing values
print("\nMissing values in the movie dataset:")
print(movies_df.isnull().sum())

# Summary statistics for ratings
print("\nSummary statistics for ratings:")
print(movies_df['Rating'].describe())

# Ratings distribution
plt.figure(figsize=(10, 6))
sns.histplot(movies_df['Rating'], bins=10, kde=False, color='skyblue', edgecolor='black')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.title('Distribution of Movie Ratings')

# Popular genres
plt.figure(figsize=(12, 8))
sns.countplot(y='Genre', data=movies_df, order=movies_df['Genre'].value_counts().index, palette='viridis')
plt.xlabel('Count')
plt.ylabel('Genre')
plt.title('Most Popular Movie Genres')

# Top-rated movies
top_rated_movies = movies_df.sort_values(by='Rating', ascending=False).head(10)
plt.figure(figsize=(12, 8))
sns.barplot(x='Rating', y='Title', data=top_rated_movies, palette='plasma')
plt.xlabel('Rating')
plt.ylabel('Movie Title')
plt.title('Top 10 Highest Rated Movies')
# Show the plots
plt.show()